"""Task/Expert bindings auto-generated by archetypes/protocol_to_task.py's pipeline from parsed protocol steps that passed automatic validation (stability + solvability over N seeds) -- see private/technical-log.md for the run that produced these. Each binding just re-invokes `build_task` on the spec that already passed; regenerating the XML here is deterministic and idempotent, not re-validation."""
from archetypes.protocol_to_task import ProtocolTaskSpec, build_task

HPLC_INJECTOR_PLUNGER_SPEC = ProtocolTaskSpec(**{'name': 'hplc_injector_plunger', 'primitive': 'conditioning', 'domain': 'analytical_chemistry', 'description': "push the HPLC autosampler's injector plunger down to load the next vial", 'moving_part_shape': 'box_vertical_slide', 'device_size': (0.09, 0.07, 0.05), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.012, 0.012, 0.02), 'part_pos': (0.0, -0.02, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.04, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.04})
HplcInjectorPlungerTask, HplcInjectorPlungerTaskExpert = build_task(HPLC_INJECTOR_PLUNGER_SPEC)

SUPERNATANT_TRANSFER_SPEC = ProtocolTaskSpec(**{'name': 'supernatant_transfer', 'primitive': 'transfer', 'domain': 'molecular_biology', 'description': 'transfer supernatant from one tube to another with a micropipette', 'moving_part_shape': 'none', 'device_size': (0.05, 0.05, 0.06), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
SupernatantTransferTask, SupernatantTransferTaskExpert = build_task(SUPERNATANT_TRANSFER_SPEC)

SPECTROPHOTOMETER_READING_SPEC = ProtocolTaskSpec(**{'name': 'spectrophotometer_reading', 'primitive': 'measurement', 'domain': 'analytical_chemistry', 'description': 'read the absorbance value from a benchtop spectrophotometer', 'moving_part_shape': 'none', 'device_size': (0.09, 0.1, 0.06), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
SpectrophotometerReadingTask, SpectrophotometerReadingTaskExpert = build_task(SPECTROPHOTOMETER_READING_SPEC)

MICROPLATE_STACKER_EJECT_SPEC = ProtocolTaskSpec(**{'name': 'microplate_stacker_eject', 'primitive': 'conditioning', 'domain': 'general_lab', 'description': "press the microplate stacker's eject button housing down to release a plate", 'moving_part_shape': 'box_vertical_slide', 'device_size': (0.1, 0.09, 0.06), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.015, 0.015, 0.015), 'part_pos': (0.06, -0.05, 0.18), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.03, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.03})
MicroplateStackerEjectTask, MicroplateStackerEjectTaskExpert = build_task(MICROPLATE_STACKER_EJECT_SPEC)

SUPERNATANT_DECANT_SPEC = ProtocolTaskSpec(**{'name': 'supernatant_decant', 'primitive': 'separation', 'domain': 'molecular_biology', 'description': 'decant clarified supernatant into a fresh vial without disturbing the pellet', 'moving_part_shape': 'none', 'device_size': (0.04, 0.04, 0.05), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
SupernatantDecantTask, SupernatantDecantTaskExpert = build_task(SUPERNATANT_DECANT_SPEC)

FREEZER_RACK_ACCESS_SPEC = ProtocolTaskSpec(**{'name': 'freezer_rack_access', 'primitive': 'preservation', 'domain': 'general_lab', 'description': 'open a freezer door to access a cryovial rack shelf', 'moving_part_shape': 'door_hinge', 'device_size': (0.12, 0.11, 0.14), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
FreezerRackAccessTask, FreezerRackAccessTaskExpert = build_task(FREEZER_RACK_ACCESS_SPEC)

BALANCE_DRAFT_SHIELD_SPEC = ProtocolTaskSpec(**{'name': 'balance_draft_shield', 'primitive': 'measurement', 'domain': 'general_lab', 'description': 'lift the draft shield lid of an analytical balance before weighing a sample', 'moving_part_shape': 'lid_hinge', 'device_size': (0.08, 0.08, 0.05), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
BalanceDraftShieldTask, BalanceDraftShieldTaskExpert = build_task(BALANCE_DRAFT_SHIELD_SPEC)

PERISTALTIC_PUMP_DIAL_SPEC = ProtocolTaskSpec(**{'name': 'peristaltic_pump_dial', 'primitive': 'conditioning', 'domain': 'general_lab', 'description': "turn the peristaltic pump's flow-rate dial to the target setting", 'moving_part_shape': 'none', 'device_size': (0.07, 0.06, 0.05), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.02), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (-0.05, 0.0), 'start_qpos': 0.0, 'target_qpos': -0.05})
PeristalticPumpDialTask, PeristalticPumpDialTaskExpert = build_task(PERISTALTIC_PUMP_DIAL_SPEC)

FILTER_CARTRIDGE_HOUSING_SPEC = ProtocolTaskSpec(**{'name': 'filter_cartridge_housing', 'primitive': 'separation', 'domain': 'chemistry', 'description': 'pull the filter cartridge housing up off the vacuum manifold', 'moving_part_shape': 'box_vertical_slide', 'device_size': (0.08, 0.08, 0.05), 'device_color': '0.75 0.78 0.8 1', 'part_size': (0.02, 0.02, 0.025), 'part_pos': (0.0, 0.0, 0.15), 'part_color': '0.2 0.2 0.2 1', 'joint_range': (0.0, 0.05), 'start_qpos': 0.0, 'target_qpos': 0.05})
FilterCartridgeHousingTask, FilterCartridgeHousingTaskExpert = build_task(FILTER_CARTRIDGE_HOUSING_SPEC)

