"""Generated mapping: real_lab_* CatalogEntry task name -> (university,
facility, discipline). Source of truth is real_lab/schools.csv (search_status
== scene_built) + the CatalogEntry notes column pointing at each task name;
regenerate by re-reading that CSV rather than hand-editing entries here.
"""

REAL_LAB_UNIVERSITIES: dict[str, dict[str, str]] = {
    "real_lab_aarhus_university_spinning_disk_display": {"university": "Aarhus University", "facility": "Department of Biomedicine / Bioimaging Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_aberdeen_university_celldiscoverer_display": {"university": "University of Aberdeen", "facility": "Microscopy and Histology Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_asu_liquid_handler_display": {"university": "Arizona State University", "facility": "Desert Southwest Genomics Center (DSGC)", "discipline": "molecular_biology_and_genomics"},
    "real_lab_aub_ngs_sequencer_display": {"university": "American University of Beirut (AUB)", "facility": "Genomic Profiling Program, Molecular Diagnostics Laboratory", "discipline": "molecular_biology_and_genomics"},
    "real_lab_basel_university_lmd_display": {"university": "University of Basel", "facility": "Imaging Core Facility (IMCF), Biozentrum", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_bern_university_lsm_display": {"university": "University of Bern", "facility": "Microscopy Imaging Center (MIC)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_bonn_limes_sted_display": {"university": "Rheinische Friedrich-Wilhelms-Universität Bonn", "facility": "LIMES Technical Platforms", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_boston_university_widefield_display": {"university": "Boston University", "facility": "Cellular Imaging Core, Evans Biomedical Research Center", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_calgary_university_afm_display": {"university": "University of Calgary", "facility": "Microscopy and Imaging Facility (Charbonneau)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_cape_town_bsc_display": {"university": "University of Cape Town", "facility": "Institute of Infectious Disease and Molecular Medicine (IDM)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_chile_university_pcr_display": {"university": "Universidad de Chile", "facility": "Laboratorio de Biologia Molecular e Ingenieria Genetica", "discipline": "molecular_biology_and_genomics"},
    "real_lab_chulalongkorn_potentiostat_display": {"university": "Chulalongkorn University", "facility": "Energetic Materials Research Laboratory", "discipline": "chemistry_and_synthesis"},
    "real_lab_curtin_university_sem_display": {"university": "Curtin University", "facility": "John de Laeter Centre", "discipline": "other_characterization"},
    "real_lab_darmstadt_aem_stem_display": {"university": "Technical University of Darmstadt", "facility": "Advanced Electron Microscopy (AEM) Division", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_dartmouth_college_dragonfly_display": {"university": "Dartmouth College", "facility": "Life Sciences Light Microscopy Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_deakin_university_sem_display": {"university": "Deakin University", "facility": "Materials Science Labs", "discipline": "chemistry_and_synthesis"},
    "real_lab_dtu_nanolab_fibsem_display": {"university": "Technical University of Denmark", "facility": "DTU Nanolab", "discipline": "chemistry_and_synthesis"},
    "real_lab_eindhoven_microfab_display": {"university": "Eindhoven University of Technology", "facility": "TU/e Microfab Lab", "discipline": "chemistry_and_synthesis"},
    "real_lab_emory_university_sequencer_display": {"university": "Emory University", "facility": "Emory Integrated Genomics Core", "discipline": "molecular_biology_and_genomics"},
    "real_lab_erasmus_rotterdam_biomics_display": {"university": "Erasmus University Rotterdam", "facility": "Erasmus Center for Biomics, Dept. of Molecular Genetics", "discipline": "molecular_biology_and_genomics"},
    "real_lab_exeter_university_em_display": {"university": "The University of Exeter", "facility": "Bioimaging Centre, Biosciences Facilities", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_fau_erlangen_cenem_display": {"university": "Friedrich-Alexander-Universität Erlangen-Nürnberg", "facility": "CENEM, Center for Nanoanalysis and Electron Microscopy", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_florida_university_flowcytometer_display": {"university": "University of Florida", "facility": "Cytometry & Optical Microscopy Core", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_freiburg_university_sted_display": {"university": "Albert-Ludwigs-Universitaet Freiburg", "facility": "Life Imaging Center (LIC)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_gadjah_mada_promethion_display": {"university": "Gadjah Mada University", "facility": "Integrated Genome Factory (IGF)", "discipline": "molecular_biology_and_genomics"},
    "real_lab_geneva_university_slide_scanner_display": {"university": "University of Geneva", "facility": "Faculty of Medicine / Bioimaging Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_gothenburg_university_maldi_display": {"university": "University of Gothenburg", "facility": "Centre for Cellular Imaging (CCI)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_groningen_university_cell_sorter_display": {"university": "University of Groningen", "facility": "Groningen Biomolecular Sciences and Biotechnology Institute (GBB)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_hamburg_university_confocal_display": {"university": "Universität Hamburg", "facility": "Technology Platform Light Microscopy", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_hbku_qbri_imagestream_display": {"university": "Hamad Bin Khalifa University", "facility": "QBRI Imaging and Flow Cytometry Core", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_helsinki_university_sequencer_display": {"university": "University of Helsinki", "facility": "DNA Sequencing and Genomics Laboratory (BIDGEN)", "discipline": "molecular_biology_and_genomics"},
    "real_lab_iisc_apt_display": {"university": "Indian Institute of Science", "facility": "Advanced Facility for Microscopy and Microanalysis (AFMM)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_iitb_nmr_display": {"university": "Indian Institute of Technology Bombay (IITB)", "facility": "Department of Chemistry shared instrumentation (IOE/RIFC/FIST)", "discipline": "chemistry_and_synthesis"},
    "real_lab_iitkgp_fesem_display": {"university": "Indian Institute of Technology Kharagpur (IIT-KGP)", "facility": "Central Research Facility (CRF)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_iitm_bioincubator_fermenter_display": {"university": "Indian Institute of Technology Madras (IITM)", "facility": "IITM Bioincubator", "discipline": "molecular_biology_and_genomics"},
    "real_lab_keio_university_multisem_display": {"university": "Keio University", "facility": "Electron Microscope Center", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_kfupm_sem_display": {"university": "King Fahd University of Petroleum & Minerals", "facility": "Chemistry Department Microscopy Laboratory", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_khalifa_university_tem_display": {"university": "Khalifa University of Science and Technology", "facility": "Research Labs Department / Electron Microscopy Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_king_saud_gammacell_display": {"university": "King Saud University", "facility": "Central Laboratory, College of Science", "discipline": "chemistry_and_synthesis"},
    "real_lab_kit_karlsruhe_tem_display": {"university": "KIT, Karlsruhe Institute of Technology", "facility": "Laboratory for Electron Microscopy (LEM)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_kyushu_university_laser_display": {"university": "Kyushu University", "facility": "Laboratory of Spectrochemistry (Onda Laboratory)", "discipline": "chemistry_and_synthesis"},
    "real_lab_lancaster_university_confocal_display": {"university": "Lancaster University", "facility": "Division of Biomedical and Life Sciences / Advanced Light Microscopy Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_leiden_university_cryoem_display": {"university": "Leiden University", "facility": "NeCEN, Gorlaeus Laboratory", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_loughborough_university_nmr_display": {"university": "Loughborough University", "facility": "Department of Chemistry / WPL.2.09 Synthesis Laboratory", "discipline": "chemistry_and_synthesis"},
    "real_lab_maryland_university_jpk_afm_display": {"university": "University of Maryland, College Park", "facility": "Imaging Core (IC), UMD Bioscience Cores", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_massey_university_abi_display": {"university": "Massey University", "facility": "Massey Genome Service", "discipline": "molecular_biology_and_genomics"},
    "real_lab_mcmaster_university_sequencer_display": {"university": "McMaster University", "facility": "McMaster Genomics Facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_minnesota_university_ctrap_display": {"university": "University of Minnesota Twin Cities", "facility": "University Imaging Centers (UIC)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_msu_quantstudio_display": {"university": "Michigan State University", "facility": "RTSF Genomics Core", "discipline": "molecular_biology_and_genomics"},
    "real_lab_nagoya_university_palm_display": {"university": "Nagoya University", "facility": "Institute of Transformative Bio-Molecules (ITbM) / Live Imaging Center", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_ncku_jem1400_display": {"university": "National Cheng Kung University (NCKU)", "facility": "TEM service, Medical Building", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_newcastle_au_orbitrap_display": {"university": "The University of Newcastle, Australia (UON)", "facility": "Central Analytical Facilities (CAF)", "discipline": "chemistry_and_synthesis"},
    "real_lab_nottingham_genomics_display": {"university": "University of Nottingham", "facility": "Post-Genomic Technologies Facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_nthu_cms_display": {"university": "National Tsing Hua University", "facility": "Confocal Microscope System (CMS) facility, Instrumentation Center", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_nycu_lsm900_display": {"university": "National Yang Ming Chiao Tung University", "facility": "Imaging Core Facility, Yang Ming Campus", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_oslo_university_livecell_display": {"university": "University of Oslo", "facility": "Advanced Light Microscopy core facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_osu_cmif_lightsheet_display": {"university": "The Ohio State University", "facility": "Campus Microscopy and Imaging Facility (CMIF)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_otago_university_jsm6700f_display": {"university": "University of Otago", "facility": "Otago Micro and Nanoscale Imaging (OMNI)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_ottawa_university_sp5sted_display": {"university": "University of Ottawa", "facility": "CBIA Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_padova_university_tem_display": {"university": "Università di Padova", "facility": "DiBio Imaging Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_polimi_flow_reactor_display": {"university": "Politecnico di Milano", "facility": "BiocatLab", "discipline": "chemistry_and_synthesis"},
    "real_lab_polito_ultrasonic_display": {"university": "Politecnico di Torino", "facility": "Chemical Synthesis Laboratory, Technological Centre Alessandria", "discipline": "chemistry_and_synthesis"},
    "real_lab_queen_mary_sequencer_display": {"university": "Queen Mary University of London", "facility": "Barts and the London Genome Centre", "discipline": "molecular_biology_and_genomics"},
    "real_lab_queens_kingston_maldi_display": {"university": "Queen's University at Kingston", "facility": "Department of Chemistry shared analytical facilities, Chernoff Hall", "discipline": "chemistry_and_synthesis"},
    "real_lab_qut_carf_him_display": {"university": "Queensland University of Technology (QUT)", "facility": "Central Analytical Research Facility (CARF)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_rice_university_mask_aligner_display": {"university": "Rice University", "facility": "Shared Equipment Authority / Rice Nanofabrication Facility", "discipline": "chemistry_and_synthesis"},
    "real_lab_rmit_university_fibsem_display": {"university": "RMIT University", "facility": "RMIT Microscopy and Microanalysis Facility (RMMF)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_rochester_university_sonicator_display": {"university": "University of Rochester", "facility": "Rochester Genomics Center, Wilmot Cancer Institute", "discipline": "molecular_biology_and_genomics"},
    "real_lab_sheffield_university_chromium_display": {"university": "The University of Sheffield", "facility": "Multiomics Facility, SITraN", "discipline": "molecular_biology_and_genomics"},
    "real_lab_st_andrews_orbitrap_display": {"university": "University of St Andrews", "facility": "School of Chemistry analytical facilities, Purdie Building", "discipline": "chemistry_and_synthesis"},
    "real_lab_stockholm_university_sps_display": {"university": "Stockholm University", "facility": "Spark Plasma Sintering Facility, Arrhenius Laboratory", "discipline": "chemistry_and_synthesis"},
    "real_lab_sussex_university_scanr_display": {"university": "University of Sussex", "facility": "Wolfson Centre for Biological Imaging (GDSC)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_tel_aviv_university_lsm510_display": {"university": "Tel Aviv University", "facility": "Rosalie and Harold Rae Brown Cancer Research Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_tohoku_university_mri_display": {"university": "Tohoku University", "facility": "ToMMo biobank/genome-medicine facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_tu_berlin_flow_cytometer_display": {"university": "Technische Universität Berlin (TU Berlin)", "facility": "Chair of Environmental Microbiomics (umbio)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_tubingen_university_em_display": {"university": "Eberhard Karls Universität Tübingen", "facility": "Tubingen Structural Microscopy (TSM) Core Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_tuwien_ustem_neoarm_display": {"university": "Technische Universität Wien", "facility": "USTEM", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_twente_university_sputter_display": {"university": "University of Twente", "facility": "MESA+ Institute for Nanotechnology / NanoLab", "discipline": "chemistry_and_synthesis"},
    "real_lab_uam_madrid_stellaris_display": {"university": "Universidad Autónoma de Madrid", "facility": "SMOA Advanced Optical Microscopy Facility, CBM", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_ucd_conway_cytometer_display": {"university": "University College Dublin", "facility": "Conway Genomics Core / Conway Imaging Core", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_uclouvain_nmr_display": {"university": "Université catholique de Louvain (UCLouvain)", "facility": "NMR Platform, IMCN", "discipline": "chemistry_and_synthesis"},
    "real_lab_ucsb_nanolive_display": {"university": "University of California, Santa Barbara (UCSB)", "facility": "NRI-MCDB Microscopy Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_ukm_pcr_display": {"university": "Universiti Kebangsaan Malaysia (UKM)", "facility": "Genomics Lab, INBIOSIS", "discipline": "molecular_biology_and_genomics"},
    "real_lab_ulb_limif_display": {"university": "Universite libre de Bruxelles", "facility": "Light Microscopy Facility (LiMiF), IRIBHM", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_unc_lightsheet_display": {"university": "University of North Carolina, Chapel Hill", "facility": "Department of Biology / Biology Microscopy Core", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_uniandes_tescan_display": {"university": "Universidad de los Andes", "facility": "Centro de Microscopia (MicroCore)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_unicamp_afm_display": {"university": "Universidade Estadual de Campinas (Unicamp)", "facility": "Institute of Chemistry / LIMicro-IQ", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_uppsala_university_multiphoton_display": {"university": "Uppsala University", "facility": "BioVis imaging core facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_usc_genomics_core_display": {"university": "University of Southern California", "facility": "Molecular Genomics Core (MGC)", "discipline": "molecular_biology_and_genomics"},
    "real_lab_usm_pfge_display": {"university": "Universiti Sains Malaysia (USM)", "facility": "INFORMM equipment facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_utrecht_university_fibsem_display": {"university": "Utrecht University", "facility": "Cell Microscopy Core (CMC)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_vanderbilt_university_esem_display": {"university": "Vanderbilt University", "facility": "Cell Imaging Shared Resource (CISR)", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_waseda_university_jem2100f_display": {"university": "Waseda University", "facility": "Analytical Instrument Laboratory, Kagami Memorial Research Institute", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_waterloo_university_gel_imager_display": {"university": "University of Waterloo", "facility": "Molecular Biology Core Facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_wellington_university_vucel_display": {"university": "Victoria University of Wellington", "facility": "Victoria University Coastal Ecology Lab (VUCEL)", "discipline": "other"},
    "real_lab_western_university_pcr_display": {"university": "Western University", "facility": "Department of Biology / Molecular Genetics Unit", "discipline": "molecular_biology_and_genomics"},
    "real_lab_wisconsin_madison_novaseq_display": {"university": "University of Wisconsin-Madison", "facility": "UW Biotech Center DNA Sequencing Facility", "discipline": "molecular_biology_and_genomics"},
    "real_lab_wuhan_university_platereader_display": {"university": "Wuhan University", "facility": "Shared Instrument Platform, College of Life Sciences", "discipline": "molecular_biology_and_genomics"},
    "real_lab_wustl_histology_display": {"university": "Washington University in St. Louis", "facility": "Molecular Microbiology Imaging Facility", "discipline": "microscopy_and_cell_manipulation"},
    "real_lab_york_university_elyra7_display": {"university": "University of York", "facility": "Technology Facility Imaging and Cytometry Laboratory", "discipline": "microscopy_and_cell_manipulation"},
}
